/*
 * Copyright (c) 2026 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#include "mesh_recipes.h"

#include <zephyr/bluetooth/mesh.h>

/*
 * light_ctrl - two-element node.
 * elem[0]: Light Lightness Server - lightness from dimmers.
 * elem[1]: Light LC Server + Generic OnOff Server - on/off from switches.
 */
static const struct mesh_setup_step light_ctrl_1_steps[] = {
	NETKEY_ADD(NET_PRIMARY),
	APPKEY_ADD(NET_PRIMARY, APPKEY_IDX),

	BIND(0, SIG_MODEL(BT_MESH_MODEL_ID_LIGHT_LIGHTNESS_SRV), APPKEY_IDX),
	SUB(0, SIG_MODEL(BT_MESH_MODEL_ID_LIGHT_LIGHTNESS_SRV), GRP_1),

	BIND(1, SIG_MODEL(BT_MESH_MODEL_ID_LIGHT_LC_SRV), APPKEY_IDX),
	BIND(1, SIG_MODEL(BT_MESH_MODEL_ID_GEN_ONOFF_SRV), APPKEY_IDX),
	SUB(1, SIG_MODEL(BT_MESH_MODEL_ID_GEN_ONOFF_SRV), GRP_1),
};

static const struct mesh_setup_step light_ctrl_2_steps[] = {
	NETKEY_ADD(NET_PRIMARY),
	APPKEY_ADD(NET_PRIMARY, APPKEY_IDX),

	BIND(0, SIG_MODEL(BT_MESH_MODEL_ID_LIGHT_LIGHTNESS_SRV), APPKEY_IDX),
	SUB(0, SIG_MODEL(BT_MESH_MODEL_ID_LIGHT_LIGHTNESS_SRV), GRP_2),

	BIND(1, SIG_MODEL(BT_MESH_MODEL_ID_LIGHT_LC_SRV), APPKEY_IDX),
	BIND(1, SIG_MODEL(BT_MESH_MODEL_ID_GEN_ONOFF_SRV), APPKEY_IDX),
	SUB(1, SIG_MODEL(BT_MESH_MODEL_ID_GEN_ONOFF_SRV), GRP_2),
};

static const struct mesh_setup_step light_sw_1_steps[] = {
	NETKEY_ADD(NET_PRIMARY),
	APPKEY_ADD(NET_PRIMARY, APPKEY_IDX),

	BIND(0, SIG_MODEL(BT_MESH_MODEL_ID_GEN_ONOFF_CLI), APPKEY_IDX),
	/* light_sw_1: element 0 publishes to GRP_1 */
	PUB(0, SIG_MODEL(BT_MESH_MODEL_ID_GEN_ONOFF_CLI), APPKEY_IDX, GRP_1, PUB_TTL,
	    PUB_PERIOD_OFF, PUB_XMIT_1x100),
};

static const struct mesh_setup_step light_sw_2_steps[] = {
	NETKEY_ADD(NET_PRIMARY),
	APPKEY_ADD(NET_PRIMARY, APPKEY_IDX),

	BIND(0, SIG_MODEL(BT_MESH_MODEL_ID_GEN_ONOFF_CLI), APPKEY_IDX),
	/* light_sw_2: element 0 publishes to GRP_2 */
	PUB(0, SIG_MODEL(BT_MESH_MODEL_ID_GEN_ONOFF_CLI), APPKEY_IDX, GRP_2, PUB_TTL,
	    PUB_PERIOD_OFF, PUB_XMIT_1x100),
};

static const struct mesh_setup_step light_dimmer_1_steps[] = {
	NETKEY_ADD(NET_PRIMARY),
	APPKEY_ADD(NET_PRIMARY, APPKEY_IDX),

	BIND(0, SIG_MODEL(BT_MESH_MODEL_ID_GEN_ONOFF_CLI), APPKEY_IDX),
	PUB(0, SIG_MODEL(BT_MESH_MODEL_ID_GEN_LEVEL_CLI), APPKEY_IDX, GRP_1, PUB_TTL,
	    PUB_PERIOD_OFF, PUB_XMIT_1x100),

	BIND(0, SIG_MODEL(BT_MESH_MODEL_ID_GEN_LEVEL_CLI), APPKEY_IDX),
	PUB(0, SIG_MODEL(BT_MESH_MODEL_ID_SCENE_CLI), APPKEY_IDX, GRP_1, PUB_TTL,
	    PUB_PERIOD_OFF, PUB_XMIT_1x100),

	BIND(0, SIG_MODEL(BT_MESH_MODEL_ID_SCENE_CLI), APPKEY_IDX),
	PUB(0, SIG_MODEL(BT_MESH_MODEL_ID_GEN_ONOFF_CLI), APPKEY_IDX, GRP_1, PUB_TTL,
	    PUB_PERIOD_OFF, PUB_XMIT_1x100),
};

static const struct mesh_setup_step light_dimmer_2_steps[] = {
	NETKEY_ADD(NET_PRIMARY),
	APPKEY_ADD(NET_PRIMARY, APPKEY_IDX),

	BIND(0, SIG_MODEL(BT_MESH_MODEL_ID_GEN_ONOFF_CLI), APPKEY_IDX),
	PUB(0, SIG_MODEL(BT_MESH_MODEL_ID_GEN_LEVEL_CLI), APPKEY_IDX, GRP_2, PUB_TTL,
	    PUB_PERIOD_OFF, PUB_XMIT_1x100),

	BIND(0, SIG_MODEL(BT_MESH_MODEL_ID_GEN_LEVEL_CLI), APPKEY_IDX),
	PUB(0, SIG_MODEL(BT_MESH_MODEL_ID_SCENE_CLI), APPKEY_IDX, GRP_2, PUB_TTL,
	    PUB_PERIOD_OFF, PUB_XMIT_1x100),

	BIND(0, SIG_MODEL(BT_MESH_MODEL_ID_SCENE_CLI), APPKEY_IDX),
	PUB(0, SIG_MODEL(BT_MESH_MODEL_ID_GEN_ONOFF_CLI), APPKEY_IDX, GRP_2, PUB_TTL,
	    PUB_PERIOD_OFF, PUB_XMIT_1x100),
};

static const struct mesh_setup_step enocean_bcast_steps[] = {
	NETKEY_ADD(NET_PRIMARY),
	APPKEY_ADD(NET_PRIMARY, APPKEY_IDX),

	BIND(0, SIG_MODEL(BT_MESH_MODEL_ID_GEN_LEVEL_CLI), APPKEY_IDX),
	BIND(0, SIG_MODEL(BT_MESH_MODEL_ID_GEN_ONOFF_CLI), APPKEY_IDX),
	PUB(0, SIG_MODEL(BT_MESH_MODEL_ID_GEN_LEVEL_CLI), APPKEY_IDX, GRP_1, PUB_TTL,
	    PUB_PERIOD_OFF, PUB_XMIT_1x100),
	PUB(0, SIG_MODEL(BT_MESH_MODEL_ID_GEN_ONOFF_CLI), APPKEY_IDX, GRP_1, PUB_TTL,
	    PUB_PERIOD_OFF, PUB_XMIT_1x100),

	BIND(1, SIG_MODEL(BT_MESH_MODEL_ID_GEN_LEVEL_CLI), APPKEY_IDX),
	BIND(1, SIG_MODEL(BT_MESH_MODEL_ID_GEN_ONOFF_CLI), APPKEY_IDX),
	PUB(1, SIG_MODEL(BT_MESH_MODEL_ID_GEN_LEVEL_CLI), APPKEY_IDX, GRP_2, PUB_TTL,
	    PUB_PERIOD_OFF, PUB_XMIT_1x100),
	PUB(1, SIG_MODEL(BT_MESH_MODEL_ID_GEN_ONOFF_CLI), APPKEY_IDX, GRP_2, PUB_TTL,
	    PUB_PERIOD_OFF, PUB_XMIT_1x100),
};

/* Recipe registry - direct-indexed by enum mesh_recipe_id. Remember to update this list */
const struct mesh_recipe mesh_recipes[RECIPE_COUNT] = {
	[RECIPE_NONE] = { 0 },
	[RECIPE_LIGHT_CTRL_1] = RECIPE_ENTRY(light_ctrl_1_steps),
	[RECIPE_LIGHT_CTRL_2] = RECIPE_ENTRY(light_ctrl_2_steps),
	[RECIPE_DIMMER_1] = RECIPE_ENTRY(light_dimmer_1_steps),
	[RECIPE_DIMMER_2] = RECIPE_ENTRY(light_dimmer_2_steps),
	[RECIPE_LIGHT_SW_1] = RECIPE_ENTRY(light_sw_1_steps),
	[RECIPE_LIGHT_SW_2] = RECIPE_ENTRY(light_sw_2_steps),
	[RECIPE_ENOCEAN_BCAST] = RECIPE_ENTRY(enocean_bcast_steps),
};
